### ISSUE TITLE
微信云函数配置wxCloudEnv怎么获取

### ISSUE THREAD

**Issue by lovezhumeimei** [sgxiang/pdd-coupon#3]
文件 functions/pquery/index.js 在 project.config.json 'cloudfunctionRoot' 指定的目录, 如果不希望在小程序/小游戏的运行环境中执行该文件，请使用 project.config.json "miniprogramRoot" 组织项目目录结构
查看文档
"https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html"
文件 functions/pquery/pdd/utils.js 在 project.config.json 'cloudfunctionRoot' 指定的目录, 如果不希望在小程序/小游戏的运行环境中执行该文件，请使用 project.config.json "miniprogramRoot" 组织项目目录结构
查看文档
"https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html"
appservice?t=1608286030821:1524 app.js:
 Error: module "env.js" is not defined
    at require (VM22 WAService.js:2)
    at VM22 WAService.js:2
    at app.js? [sm]:3
    at wrapFn (appservice?t=1608286030821:1517)
    at require (VM22 WAService.js:2)
    at <anonymous>:3:7
    at doWhenAllScriptLoaded (appservice?t=1608286030821:1662)
    at HTMLScriptElement.scriptLoaded (appservice?t=1608286030821:1682)
    at HTMLScriptElement.script.onload (appservice?t=1608286030821:1690)
wrapFn @ appservice?t=1608286030821:1524
require @ VM22 WAService.js:2
(anonymous) @ VM40:3
doWhenAllScriptLoaded @ appservice?t=1608286030821:1662
scriptLoaded @ appservice?t=1608286030821:1682
script.onload @ appservice?t=1608286030821:1690
VM22 WAService.js:2 MiniProgramError
module "env.js" is not defined
Error: module "env.js" is not defined
    at require (http://127.0.0.1:43135/appservice/__dev__/WAService.js:2:3253765)
    at http://127.0.0.1:43135/appservice/__dev__/WAService.js:2:3253161
    at http://127.0.0.1:43135/appservice/app.js:4:12
    at wrapFn (http://127.0.0.1:43135/appservice/appservice?t=1608286030821:1517:12)
    at require (http://127.0.0.1:43135/appservice/__dev__/WAService.js:2:3253998)
    at <anonymous>:3:7
    at doWhenAllScriptLoaded (http://127.0.0.1:43135/appservice/appservice?t=1608286030821:1662:21)
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:43135/appservice/appservice?t=1608286030821:1682:5)
    at HTMLScriptElement.script.onload (http://127.0.0.1:43135/appservice/appservice?t=1608286030821:1690:20)
errorReport @ VM22 WAService.js:2
thirdErrorReport @ VM22 WAService.js:2
(anonymous) @ VM22 WAService.js:2
u @ VM22 WAService.js:2
n @ VM22 WAService.js:2
(anonymous) @ VM22 WAService.js:2
value @ VM22 WAService.js:2
(anonymous) @ VM22 WAService.js:2
doWhenAllScriptLoaded @ appservice?t=1608286030821:1662
scriptLoaded @ appservice?t=1608286030821:1682
script.onload @ appservice?t=1608286030821:1690
[sitemap 索引情况提示] 根据 sitemap 的规则[0]，当前页面 [pages/index/index] 将被索引
[ appservice 生成错误] env.js: file: env.js
 env.js: Unexpected token (9:2)
    7 |     path: "/pages/index/index",
   8 |   },
>  9 |   ],
     |  ^
  10 |   // 拼多多appid
  11 |   pddAppId: "wx32540bd863b27570",
  12 |   // 首页子分类进去的详情页顶部banner图片地址
VM22 WAService.js:2 Page "pages/index/index" has not been registered yet.

**Comment by sgxiang** [comment]
开发工具中点击云开发，在设置那里就可以找到环境ID
